server:
  port: 8888

spring:
  application:
    name: gateway-application

  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      globalcors:
        # gateway 跨域设置
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: hqkh # 路由的编号
          uri: http://192.168.1.198:8801/hqkh # 路由到的目标地址
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/hqkh/**
          filters:
            - StripPrefix=1
        - id: mqtt # 路由的编号
          uri: http://192.168.1.147:8161 # 路由的目标地址
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/
          filters: # 过滤器，对请求进行拦截，实现自定义的功能，对应 FilterDefinition 数组
            - StripPrefix=1
#            - StripPrefix=200
#      default-filters:
#        - StripPrefix=1
#        - StripPrefix=2
#        - StripPrefix=3

#      httpserver:
#        wiretap: true
#      httpclient:
#        wiretap: true

logging:
  level:
    reactor.netty: DEBUG
    org.springframework.cloud.gateway: TRACE
#    org.springframework.web.reactive: TRACE
