server:
  ssl:
    enabled: false
    key-alias: tomcat
    #key-password: 111111
    key-store: classpath:httpsConfig/keystore.p12
    key-store-type: PKCS12
    key-store-password: 111111
  port: 8801
  servlet:
    context-path: /
spring:
  redis:
    database: 3
    host: 192.168.1.147
    port: 6379
    timeout: 30000
    password: pufin@803
  #  security:
#    user:
#      name: admin
#      password: test
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:postgresql://192.168.1.152:5432/ykkj-flowable # postgres Ykkj0335P!
    url: jdbc:mysql://192.168.1.147:3308/ykkj-demo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: welcome
  # ActiveMQ 配置项，对应 ActiveMQProperties 配置类
  activemq:
    broker-url: tcp://192.168.1.147:61616 # ActiveMQ Broker 的地址
    user: admin # 账号
    password: admin # 密码
    pub-sub-domain: true
    packages:
      trust-all: true # 可信任的反序列化包
  reactor:
    debug-agent:
      enabled:

nacos:
  config:
    server-addr: 192.168.1.147:8848
    enabled: false
  discovery:
    server-addr: 192.168.1.147:8848
    enabled: false

cloud:
  huawei:
    obs:
      accessKeyId: 3
      secretAccessKeyId: 1
      endPoint: 2
      bucketName : 2


flowable:
  jpa-enabled: false
  app:
    enabled: false
  dmn:
    enabled: false
#  rest:
#    app:
#      authentication-mode: no-privilege
#      #  idm:
#      admin:
#        password: test
#        user-id: admin
#        first-name: admin
#        last-name: admin
#  #关闭定时任务JOB
#  async-executor-activate: false
#  database-schema-update: true # 设置为 false，可通过 https://github.com/flowable/flowable-sql 初始化
#  db-history-used: false # flowable6 默认 true 生成信息表，无需手动设置
#  check-process-definitions: false # 设置为 false，禁用 /resources/processes 自动部署 BPMN XML 流程
#  history-level: full # full：保存历史数据的最高级别，可保存全部流程相关细节，包括流程流转各节点参数
license:
  subject: license
  publicAlias: publicCert
  storePass: public_password1234